default: &default
  adapter: postgresql
  user: username
  password: 123
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_name_development
test:
  <<: *default
  database: app_name_test

production:
  database: app_name_production
  url: <%= ENV["DATABASE_URL"] %>
